### ISSUE TITLE
A question about the fully train step of CARS for the Cutsom ClassificationDataset. Thanks!

### ISSUE THREAD

**Issue by YTW0518** [huawei-noah/vega#110]
When I use the classification data set defined by myself, there is no problem in the NAS step, but in the fully train step, there is a problem of feature size mismatch, as follows: 
(the classification image size is 256×256×3, the num_classes is 21, the batch_size in train is 2)
Looking forward to your reply, thank you very very much!!!

INFO Clean worker folder /home/wyt/tasks/0512.004010.920/workers/nas.
INFO ------------------------------------------------
INFO   Step: fully_train
INFO ------------------------------------------------
INFO init TrainPipeStep...
INFO TrainPipeStep started...
INFO Model was created.
ERROR Failed to run pipeline.
ERROR Traceback (most recent call last):
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/pipeline/pipeline.py", line 69, in run
    PipeStep().do()
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/pipeline/train_pipe_step.py", line 50, in do
    self._train_multi_models(records)
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/pipeline/train_pipe_step.py", line 121, in _train_multi_models
    self._train_single_model(record.desc, record.worker_id, weights_file)
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/pipeline/train_pipe_step.py", line 95, in _train_single_model
    self._do_single_fully_train(trainer)
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/pipeline/train_pipe_step.py", line 114, in _do_single_fully_train
    self._train_single_gpu_model(trainer)
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/pipeline/train_pipe_step.py", line 99, in _train_single_gpu_model
    self.master.run(trainer, evaluator)
  File "/home/wyt/.local/lib/python3.7/site-packages/vega/core/scheduler/local_master.py", line 47, in run
    worker.train_process()
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/trainer/trainer_base.py", line 133, in train_process
    self._train_loop()
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/trainer/trainer_base.py", line 308, in _train_loop
    self._train_epoch()
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/trainer/trainer_torch.py", line 102, in _train_epoch
    train_batch_output = self.train_step(batch)
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/trainer/trainer_torch.py", line 155, in _default_train_step
    output = self.model(input)
  File "/home/wyt/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/modules/operators/functions/pytorch_fn.py", line 128, in forward
    return self.call(inputs, *args, **kwargs)
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/networks/super_network.py", line 95, in call
    logits_aux = self.auxiliary_head(s1)
  File "/home/wyt/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/modules/operators/functions/pytorch_fn.py", line 128, in forward
    return self.call(inputs, *args, **kwargs)
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/modules/operators/functions/pytorch_fn.py", line 106, in call
    output = model(output)
  File "/home/wyt/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wyt/.local/lib/python3.7/site-packages/zeus/modules/operators/functions/pytorch_fn.py", line 395, in forward
    out = super().forward(x)
  File "/home/wyt/.local/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/wyt/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [2 x 277248], m2: [768 x 21] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290

**Comment by zhangjiajin** [comment]
@YTW0518 

Hi, please modify the template and resize the image, as follows:

```yaml
nas:
    trainer:
        type: Trainer
        darts_template_file: "{default_darts_imagenet_template}"

fully_train:
    dataset:
        ref: nas.dataset
        common:
            train_portion: 1.0
        train:
            batch_size: 96
            shuffle: True
            transforms:
                -   type: Resize
                    size: [256, 256]
                -   type: RandomCrop
                    size: [224, 224]
                -   type: RandomHorizontalFlip
                -   type: ToTensor
                -   type: Normalize
                    mean:
                        - 0.49139968
                        - 0.48215827
                        - 0.44653124
                    std:
                        - 0.24703233
                        - 0.24348505
                        - 0.26158768
        val:
            batch_size: 96
            shuffle: False
            transforms:
                -   type: Resize
                    size: [224, 224]
                -   type: ToTensor
                -   type: Normalize
                    mean:
                        - 0.49139968
                        - 0.48215827
                        - 0.44653124
                    std:
                        - 0.24703233
                        - 0.24348505
                        - 0.26158768
        test:
            batch_size: 96
            shuffle: False
            transforms:
                -   type: Resize
                    size: [224, 224]
                -   type: ToTensor
                -   type: Normalize
                    mean:
                        - 0.49139968
                        - 0.48215827
                        - 0.44653124
                    std:
                        - 0.24703233
                        - 0.24348505
                        - 0.26158768
```
