### ISSUE TITLE
CycleSR can not be reimplemented

### ISSUE THREAD

**Issue by greatlog** [huawei-noah/vega#121]
Hi, I cannot get the reported results of CycleSR on NTIRE2017 Track2. The reported PSNR is 27.01 dB, while the reimplemented result is only 22 dB. Can you provide the pretrained weights of all modules in CycleSR?

**Comment by zhangjiajin** [comment]
@greatlog 

Please adjust the configuration. After the modification, the performance can be greater than 25 dB.

```yaml
    dataset:
        train:
            batch_size: 64
        test:
            batch_size: 64

    trainer:
        n_epoch: 150
```
