### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Prokrus** [huawei-noah/vega#194]
When run the example: _vega  car.yaml_, it comes the error: cudnn error: CUDNN_STATUS_EXECUTION_FAILED.

I run the example in conda enviroment.
cudatoolkit: 10.0
cudnn: 7.6.5
torch: 1.3.0

**Comment by zhangjiajin** [comment]
What kind of accelerator card are you using? V100, or 3070?
If the value is not V100, reduce the values of num_workers and batchsize.

```yaml
    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            train_portion: 0.5
            num_workers: 8    # <- 0
            drop_last: False
        train:
            shuffle: True
            batch_size: 128   # <- 64 or 32
        val:
            batch_size: 3500  # <- 128
```
